import Foundation

/// Sample catalogue used when Firestore has no vehicles yet, and as the payload
/// for the debug "Seed Firestore" action.
enum SeedData {
    static let vehicles: [Vehicle] = [
        Vehicle(
            id: "v001",
            name: "Toyota Aqua",
            brand: "Toyota",
            category: .sedan,
            dailyPrice: 8500,
            imageURL: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .hybrid,
            transmission: .automatic,
            seats: 5,
            includedMileage: 250,
            description: "Frugal hybrid hatchback that is ideal for airport runs and everyday city errands.",
            specifications: [
                "Engine": "1.5L Hybrid",
                "Fuel Economy": "27 km/l",
                "Body": "Hatchback",
                "Air Conditioning": "Yes"
            ],
            isAvailable: true,
            rating: 4.6,
            reviewCount: 184,
            location: Branch.katunayakeAirport.rawValue
        ),
        Vehicle(
            id: "v002",
            name: "Toyota Premio",
            brand: "Toyota",
            category: .sedan,
            dailyPrice: 12000,
            imageURL: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 200,
            description: "Comfortable executive sedan for long-distance business travel and family trips.",
            specifications: [
                "Engine": "1.5L Petrol",
                "Transmission": "Automatic",
                "Body": "Sedan",
                "Boot Space": "440 L"
            ],
            isAvailable: true,
            rating: 4.5,
            reviewCount: 142,
            location: Branch.kurunegala.rawValue
        ),
        Vehicle(
            id: "v003",
            name: "Ford Mustang GT",
            brand: "Ford",
            category: .sports,
            dailyPrice: 52000,
            imageURL: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
            passengerCapacity: 2,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 2,
            includedMileage: 120,
            description: "V8 muscle car hired for weddings, photo shoots and weekend coastal drives.",
            specifications: [
                "Engine": "5.0L V8",
                "Horsepower": "450 hp",
                "0-100 km/h": "4.3 s",
                "Drivetrain": "Rear-wheel drive"
            ],
            isAvailable: true,
            rating: 4.8,
            reviewCount: 76,
            location: Branch.negombo.rawValue,
            bookedPeriods: [DateRange(start: Date().adding(days: 6), end: Date().adding(days: 9))]
        ),
        Vehicle(
            id: "v004",
            name: "Volkswagen Beetle",
            brand: "Volkswagen",
            category: .sedan,
            dailyPrice: 10500,
            imageURL: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 200,
            description: "Compact retro-styled car that is easy to park for short city rentals.",
            specifications: [
                "Engine": "1.4L Petrol",
                "Transmission": "Automatic",
                "Body": "Hatchback",
                "Seats": "5"
            ],
            isAvailable: true,
            rating: 4.3,
            reviewCount: 88,
            location: Branch.negombo.rawValue
        ),
        Vehicle(
            id: "v005",
            name: "Land Rover Discovery",
            brand: "Land Rover",
            category: .suv,
            dailyPrice: 28000,
            imageURL: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .diesel,
            transmission: .automatic,
            seats: 5,
            includedMileage: 180,
            description: "Capable 4x4 SUV suited to hill-country roads and rough rural tracks.",
            specifications: [
                "Engine": "3.0L Turbo Diesel",
                "Drivetrain": "All-wheel drive",
                "Ground Clearance": "207 mm",
                "Body": "SUV"
            ],
            isAvailable: true,
            rating: 4.7,
            reviewCount: 119,
            location: Branch.kurunegala.rawValue
        ),
        Vehicle(
            id: "v006",
            name: "Toyota RAV4",
            brand: "Toyota",
            category: .suv,
            dailyPrice: 16500,
            imageURL: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .hybrid,
            transmission: .automatic,
            seats: 5,
            includedMileage: 220,
            description: "Family crossover that is a dependable choice for multi-day tours around the island.",
            specifications: [
                "Engine": "2.5L Hybrid",
                "Drivetrain": "All-wheel drive",
                "Body": "Crossover SUV",
                "Fuel Economy": "20 km/l"
            ],
            isAvailable: true,
            rating: 4.7,
            reviewCount: 203,
            location: Branch.colombo.rawValue
        ),
        Vehicle(
            id: "v007",
            name: "Tesla Model 3",
            brand: "Tesla",
            category: .electric,
            dailyPrice: 30000,
            imageURL: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .electric,
            transmission: .automatic,
            seats: 5,
            includedMileage: 300,
            description: "Zero-emission electric sedan best for Colombo commuting and short highway hops.",
            specifications: [
                "Range": "430 km",
                "Battery": "75 kWh",
                "Charging": "Type 2 / Supercharger",
                "0-100 km/h": "5.6 s"
            ],
            isAvailable: true,
            rating: 4.8,
            reviewCount: 131,
            location: Branch.gampaha.rawValue
        ),
        Vehicle(
            id: "v008",
            name: "Lamborghini Huracan Spyder",
            brand: "Lamborghini",
            category: .luxury,
            dailyPrice: 60000,
            imageURL: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&q=80",
            passengerCapacity: 2,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 2,
            includedMileage: 100,
            description: "Open-top supercar reserved for photo shoots and special occasions.",
            specifications: [
                "Engine": "5.2L V10",
                "Horsepower": "610 hp",
                "0-100 km/h": "3.1 s",
                "Drivetrain": "All-wheel drive"
            ],
            isAvailable: true,
            rating: 4.9,
            reviewCount: 41,
            location: Branch.negombo.rawValue
        ),
        Vehicle(
            id: "v009",
            name: "BMW 5 Series",
            brand: "BMW",
            category: .luxury,
            dailyPrice: 45000,
            imageURL: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 150,
            description: "Executive luxury sedan used for corporate travel and VIP airport transfers.",
            specifications: [
                "Engine": "2.0L Turbo Petrol",
                "Horsepower": "252 hp",
                "Transmission": "8-speed Automatic",
                "Interior": "Leather"
            ],
            isAvailable: true,
            rating: 4.9,
            reviewCount: 97,
            location: Branch.colombo.rawValue,
            bookedPeriods: [DateRange(start: Date().adding(days: 12), end: Date().adding(days: 15))]
        ),
        Vehicle(
            id: "v010",
            name: "Porsche Panamera",
            brand: "Porsche",
            category: .luxury,
            dailyPrice: 55000,
            imageURL: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 120,
            description: "High-performance grand tourer for clients who want speed with four-door comfort.",
            specifications: [
                "Engine": "4.0L V8",
                "Horsepower": "473 hp",
                "0-100 km/h": "3.6 s",
                "Interior": "Leather"
            ],
            isAvailable: true,
            rating: 4.8,
            reviewCount: 52,
            location: Branch.katunayakeAirport.rawValue
        ),
        Vehicle(
            id: "v011",
            name: "Volkswagen Type 2 Bus",
            brand: "Volkswagen",
            category: .van,
            dailyPrice: 18000,
            imageURL: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
            passengerCapacity: 7,
            fuelType: .petrol,
            transmission: .manual,
            seats: 7,
            includedMileage: 150,
            description: "Retro 7-seater van that is a favourite for scenic group road trips.",
            specifications: [
                "Engine": "1.6L Flat-4",
                "Body": "Classic Van",
                "Seats": "7",
                "Luggage": "Rear compartment"
            ],
            isAvailable: true,
            rating: 4.4,
            reviewCount: 58,
            location: Branch.kurunegala.rawValue
        ),
        Vehicle(
            id: "v012",
            name: "Nissan Caravan",
            brand: "Nissan",
            category: .van,
            dailyPrice: 19500,
            imageURL: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=800&q=80",
            passengerCapacity: 10,
            fuelType: .diesel,
            transmission: .manual,
            seats: 10,
            includedMileage: 200,
            description: "Diesel people carrier built for large families and staff shuttle runs.",
            specifications: [
                "Engine": "2.5L Turbo Diesel",
                "Body": "Passenger Van",
                "Seats": "10",
                "Air Conditioning": "Dual zone"
            ],
            isAvailable: true,
            rating: 4.3,
            reviewCount: 74,
            location: Branch.jaEla.rawValue
        ),
        Vehicle(
            id: "v013",
            name: "Tesla Model Y",
            brand: "Tesla",
            category: .electric,
            dailyPrice: 34000,
            imageURL: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .electric,
            transmission: .automatic,
            seats: 5,
            includedMileage: 300,
            description: "Electric crossover for quiet, zero-fuel city driving and airport pickups.",
            specifications: [
                "Range": "505 km",
                "Battery": "82 kWh",
                "Charging": "DC fast charge",
                "Cargo Space": "854 L"
            ],
            isAvailable: true,
            rating: 4.7,
            reviewCount: 66,
            location: Branch.jaEla.rawValue
        ),
        Vehicle(
            id: "v014",
            name: "Chevrolet Corvette",
            brand: "Chevrolet",
            category: .sports,
            dailyPrice: 55000,
            imageURL: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=800&q=80",
            passengerCapacity: 2,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 2,
            includedMileage: 100,
            description: "Two-seat performance coupe hired for track days and photography shoots.",
            specifications: [
                "Engine": "6.2L V8",
                "Horsepower": "495 hp",
                "0-100 km/h": "3.0 s",
                "Drivetrain": "Rear-wheel drive"
            ],
            isAvailable: true,
            rating: 4.8,
            reviewCount: 47,
            location: Branch.gampaha.rawValue
        ),
        Vehicle(
            id: "v015",
            name: "Hyundai Elantra",
            brand: "Hyundai",
            category: .sedan,
            dailyPrice: 13500,
            imageURL: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 220,
            description: "Modern automatic sedan that works well as a comfortable daily rental.",
            specifications: [
                "Engine": "1.6L Petrol",
                "Transmission": "Automatic",
                "Body": "Sedan",
                "Infotainment": "8-inch touchscreen"
            ],
            isAvailable: true,
            rating: 4.4,
            reviewCount: 96,
            location: Branch.colombo.rawValue,
            bookedPeriods: [
                DateRange(start: Date().adding(days: 2), end: Date().adding(days: 5)),
                DateRange(start: Date().adding(days: 18), end: Date().adding(days: 20))
            ]
        ),
        Vehicle(
            id: "v016",
            name: "Honda CR-V",
            brand: "Honda",
            category: .suv,
            dailyPrice: 14500,
            imageURL: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .hybrid,
            transmission: .automatic,
            seats: 5,
            includedMileage: 200,
            description: "Spacious hybrid SUV that keeps long family journeys economical and comfortable.",
            specifications: [
                "Engine": "2.0L Hybrid",
                "Drivetrain": "All-wheel drive",
                "Body": "SUV",
                "Fuel Economy": "18 km/l"
            ],
            isAvailable: true,
            rating: 4.8,
            reviewCount: 214,
            location: Branch.katunayakeAirport.rawValue,
            bookedPeriods: [DateRange(start: Date().adding(days: 3), end: Date().adding(days: 7))]
        ),
        Vehicle(
            id: "v017",
            name: "Toyota HiAce",
            brand: "Toyota",
            category: .van,
            dailyPrice: 22000,
            imageURL: "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&q=80",
            passengerCapacity: 14,
            fuelType: .diesel,
            transmission: .manual,
            seats: 14,
            includedMileage: 250,
            description: "Fourteen-seat diesel van that is the standard choice for tour groups and office transport.",
            specifications: [
                "Engine": "3.0L Turbo Diesel",
                "Body": "High-roof Van",
                "Seats": "14",
                "Air Conditioning": "Front and rear"
            ],
            isAvailable: false,
            rating: 4.5,
            reviewCount: 187,
            location: Branch.gampaha.rawValue
        ),
        Vehicle(
            id: "v018",
            name: "Mercedes-Benz C200",
            brand: "Mercedes-Benz",
            category: .luxury,
            dailyPrice: 42000,
            imageURL: "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80",
            passengerCapacity: 5,
            fuelType: .petrol,
            transmission: .automatic,
            seats: 5,
            includedMileage: 150,
            description: "Premium German sedan used for chauffeured airport transfers and VIP guests.",
            specifications: [
                "Engine": "2.0L Turbo Petrol",
                "Horsepower": "204 hp",
                "Interior": "Leather",
                "Transmission": "9-speed Automatic"
            ],
            isAvailable: true,
            rating: 4.9,
            reviewCount: 112,
            location: Branch.negombo.rawValue
        )
    ]
}
